/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package control.escolar.avanzado;

import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.github.sarxos.webcam.WebcamResolution;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ButtonGroup;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author josea
 */
public class EditRegAlums extends javax.swing.JFrame {

    //variables globales utilizadas

    ButtonGroup g = new ButtonGroup();

    int largoCamara = 300;
    int anchoCamara = 370;
    String DirIMG = null;
    BufferedImage ruta;
    Dimension dimension = new Dimension(anchoCamara, largoCamara);
    Dimension dimension1 = WebcamResolution.VGA.getSize();
    Webcam webcam = Webcam.getDefault();
    WebcamPanel webcampanel = new WebcamPanel(webcam, dimension, false);
    int c = 0;

    /**
     * Creates new form EditRegAlums
     */
    public EditRegAlums() {
        initComponents();
        this.setLocationRelativeTo(null);
        g.add(jRadioButton2);
        g.add(jRadioButton1);
        webcam.setViewSize(dimension1);
        webcampanel.setFillArea(true);
        pnlCamara.setLayout(new FlowLayout());
        pnlCamara.add(webcampanel);
        lbNombredelacamara.setText(webcam.toString());
        apagarBotones();
        btnOn.setEnabled(false);jPanel5.setVisible(false);
    }
//funcion para inhabilitar los botones

    public void apagarBotones() {
        btnOff.setEnabled(false);
        btnTomar.setEnabled(false);
        btnSave.setEnabled(false);
    }
//funcion para habilitar los botones

    public void encenderBotones() {
        btnOff.setEnabled(true);
        btnTomar.setEnabled(true);
    }
//funcion para apagar laq camara

    private void apagar() {
        webcampanel.stop();
        apagarBotones();
        btnOn.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BusReg = new javax.swing.JButton();
        ActDat = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        noCon = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        LblFoto = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Esp = new javax.swing.JComboBox<String>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        numCont = new javax.swing.JLabel();
        nom = new javax.swing.JLabel();
        ape = new javax.swing.JLabel();
        curp = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        grupo = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnOn = new javax.swing.JButton();
        btnOff = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        lbNombredelacamara = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        pnlCamara = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnTomar = new javax.swing.JButton();
        lbFoto = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 910, 20));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 20, 560));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Tabla de edicion de registro de alumnos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 450, 40));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Ingrese el No. de Control para cambiar sus datos: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        BusReg.setText("Buscar registro");
        BusReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusRegActionPerformed(evt);
            }
        });
        jPanel1.add(BusReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, -1, -1));

        ActDat.setText("Actualizar datos");
        ActDat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActDatActionPerformed(evt);
            }
        });
        jPanel1.add(ActDat, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, -1));

        jButton3.setText("Cerrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 70, -1));
        jPanel1.add(noCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 190, 30));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LblFoto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblFoto.setText(".");
        jPanel4.add(LblFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 240, 240));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Curp: ");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Apellidos: ");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Nombre: ");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Foto:");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Turno: ");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Grupo: ");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Especialidad: ");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        Esp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Programacion", "Administracion", "Construccion" }));
        jPanel4.add(Esp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 150, -1));

        jRadioButton1.setText("Matutino");
        jPanel4.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jRadioButton2.setText("Vespertino");
        jPanel4.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        numCont.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        numCont.setText(".");
        jPanel4.add(numCont, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 160, -1));

        nom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nom.setText(".");
        jPanel4.add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 150, -1));

        ape.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ape.setText(".");
        jPanel4.add(ape, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 150, -1));

        curp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        curp.setText(".");
        jPanel4.add(curp, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 210, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("No. Control: ");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));
        jPanel4.add(grupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 190, 30));

        jButton4.setText("Tomar foto");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, -1, -1));

        jButton5.setText("Seleccionar Imagen");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 750, 370));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 24))); // NOI18N

        btnOn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/button_turn_on_15006.png"))); // NOI18N
        btnOn.setText("Encender Camara");
        btnOn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOnActionPerformed(evt);
            }
        });

        btnOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/powerbuttonsymbol_116458.png"))); // NOI18N
        btnOff.setText("Apagar Camara");
        btnOff.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOff.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOffActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel16.setText("Camara en uso");

        lbNombredelacamara.setText(":");

        jButton6.setText("Cerrar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnOff, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNombredelacamara, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnOn)
                .addGap(104, 104, 104)
                .addComponent(btnOff)
                .addGap(35, 35, 35)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(lbNombredelacamara, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton6)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 183, 579));

        pnlCamara.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnlCamaraLayout = new javax.swing.GroupLayout(pnlCamara);
        pnlCamara.setLayout(pnlCamaraLayout);
        pnlCamaraLayout.setHorizontalGroup(
            pnlCamaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );
        pnlCamaraLayout.setVerticalGroup(
            pnlCamaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jPanel5.add(pnlCamara, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 370, 300));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save_14706.png"))); // NOI18N
        btnSave.setText("Guardar");
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnTomar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/camara_7203.png"))); // NOI18N
        btnTomar.setText("Tomar Foto");
        btnTomar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTomar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTomarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnTomar, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnTomar)
                    .addComponent(btnSave))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, 753, -1));

        lbFoto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.add(lbFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 150, 232, 219));

        jSeparator1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 15, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//btn para regresar al menu
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Menu men = new Menu();
        men.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed
//btn para buscar y extraer los datos solicitados en la base de datos
    private void BusRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusRegActionPerformed
        //"SELECT * FROM `empleados` WHERE `NoControl` = "+noCon;

        try {

            String consultar = "SELECT NoControl, Nombre, Apellido, Curp, Imagen FROM `alumnos` WHERE `NoControl` = " + noCon.getText();

            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(consultar);

            if (rs.next()) {

                numCont.setText(rs.getString("NoControl"));
                nom.setText(rs.getString("Nombre"));
                ape.setText(rs.getString("Apellido"));
                curp.setText(rs.getString("Curp"));
                Blob blob = rs.getBlob("Imagen");

                byte[] Data = blob.getBytes(1, (int) blob.length());
                BufferedImage IMG = null;
                try {
                    IMG = ImageIO.read(new ByteArrayInputStream(Data));
                } catch (Exception e) {
                    System.out.println(e);
                }
                ImageIcon icon = new ImageIcon(IMG);
                LblFoto.setIcon(icon);
            }

        } catch (SQLException ex) {
        }

    }//GEN-LAST:event_BusRegActionPerformed
//btn para habilitar la pestaña de la camara
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jPanel1.setVisible(false);
        btnOn.setEnabled(true);
        jPanel5.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed
//funcion para encender la camara
    private void btnOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOnActionPerformed

        //hilos
        Thread hilo = new Thread() {

            @Override
            public void run() {
                webcampanel.start();
            }
        };
        hilo.setDaemon(true);
        hilo.start();
        btnOn.setEnabled(false);

        encenderBotones();
    }//GEN-LAST:event_btnOnActionPerformed
    //btn para apagar la camara
    private void btnOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOffActionPerformed
        apagar();
    }//GEN-LAST:event_btnOffActionPerformed
//funcion para guardar la foto capturada
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        int pregunta = JOptionPane.showConfirmDialog(this, "¿Guardar foto?", "pregunta", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (pregunta == 0) {
            File salidaImagen = new File("C:\\Fotos\\archivo.jpg");
            try {
                ImageIO.write(ruta, "jpg", salidaImagen);
                DirIMG = String.valueOf(salidaImagen);
                Image foto = getToolkit().getImage(String.valueOf(salidaImagen));
                foto = foto.getScaledInstance(300, 300, Image.SCALE_DEFAULT);

                LblFoto.setIcon(new ImageIcon(foto));
            } catch (Exception e) {
            }
        }
        lbFoto.setIcon(null);
        apagar();
        jPanel5.setVisible(false);
        btnOn.setEnabled(false);
        jPanel1.setVisible(true);
    }//GEN-LAST:event_btnSaveActionPerformed
//funcion para tomar la foto
    private void btnTomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTomarActionPerformed
        btnSave.setEnabled(true);
        ImageIcon foto;
        foto = new ImageIcon(webcam.getImage());
        Icon iconoFoto = new ImageIcon(foto.getImage().getScaledInstance(lbFoto.getWidth(), lbFoto.getHeight(), Image.SCALE_SMOOTH));
        lbFoto.setIcon(iconoFoto);
        ruta = webcam.getImage();
    }//GEN-LAST:event_btnTomarActionPerformed
//Funcion para actualizar la base de datos
    private void ActDatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActDatActionPerformed
        try {
            FileInputStream archivofoto;
            File nombre = new File(DirIMG);
            archivofoto = new FileInputStream(nombre);
            String sql = "UPDATE alumnos SET NoControl = ?, "
                    + "Nombre = ?,"
                    + "Apellido = ?,"
                    + "Curp = ?,"
                    + "Turno = ?,"
                    + "Grupo = ?,"
                    + "Especialidad = ?,"
                    + "imagen=?"
                    + "WHERE NoControl = '" + numCont.getText() + "'";

            PreparedStatement pst = cn.prepareStatement(sql);
            pst.setString(1, numCont.getText());
            pst.setString(2, nom.getText());
            pst.setString(3, ape.getText());
            pst.setString(4, curp.getText());
            if (jRadioButton1.isSelected()) {
                pst.setString(5, "Matutino");
            } else {
                pst.setString(5, "Vespertino");
            }
            pst.setString(6, grupo.getText());
            pst.setString(7, Esp.getSelectedItem().toString());
            archivofoto = new FileInputStream(DirIMG);
            pst.setBinaryStream(8, archivofoto);

            int n = pst.executeUpdate();
            if (n > 0) {
                JOptionPane.showMessageDialog(null, "Datos actualizados con exito");

                DirIMG = null;
                LblFoto.setIcon(null);
            } else {
                JOptionPane.showMessageDialog(null, "Hubo error en el momento de actualizar los datos");
            }
        } catch (SQLException ex) {
        } catch (FileNotFoundException ex) {
        }

    }//GEN-LAST:event_ActDatActionPerformed
    //funcion para seleccionar imagen
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        JFileChooser archivo = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Formatos de Archivos JPEG(*.JPG;*.JPEG)", "jpg", "jpeg");
        archivo.setFileFilter(filtro);
        archivo.addChoosableFileFilter(filtro);
        archivo.setDialogTitle("Abrir Archivo");
        int ventana = archivo.showOpenDialog(null);
        if (ventana == JFileChooser.APPROVE_OPTION) {
            File file = archivo.getSelectedFile();
            DirIMG = String.valueOf(file);
            Image foto = getToolkit().getImage(String.valueOf(file));
            foto = foto.getScaledInstance(300, 300, Image.SCALE_DEFAULT);
            LblFoto.setIcon(new ImageIcon(foto));
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        apagar();
        jPanel5.setVisible(false);
        btnOn.setEnabled(false);
        jPanel1.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditRegAlums.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditRegAlums.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditRegAlums.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditRegAlums.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditRegAlums().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActDat;
    private javax.swing.JButton BusReg;
    private javax.swing.JComboBox<String> Esp;
    private javax.swing.JLabel LblFoto;
    private javax.swing.JLabel ape;
    private javax.swing.JButton btnOff;
    private javax.swing.JButton btnOn;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnTomar;
    private javax.swing.JLabel curp;
    private javax.swing.JTextField grupo;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbFoto;
    private javax.swing.JLabel lbNombredelacamara;
    private javax.swing.JTextField noCon;
    private javax.swing.JLabel nom;
    private javax.swing.JLabel numCont;
    private javax.swing.JPanel pnlCamara;
    // End of variables declaration//GEN-END:variables
    Conectar cc = new Conectar();
    Connection cn = cc.Conexion();
}
